#Puerto del servidor
server.port=8080
# Nombre de la aplicacion
spring.application.name=Eminent

# Configuración de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Eminent
spring.datasource.username=postgres

#utiliza la contraseña de tu base de datos
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#creacion y actualización de tablas #validate= verificar qe coincida con la bd, update= actualiza la bd
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar los JWT
jwt.secret=${JWT_SECRET}
